source "https://github.com/CocoaPods/Specs.git"

platform :ios, "8.3"
use_frameworks!

target "TPPDF_Example" do
    pod "TPPDF", :path => "../"

    target "TPPDF_Tests" do
        inherit! :search_paths

        pod "Quick"
        pod "Nimble"
    end
end
