inhibit_all_warnings!
platform :ios, '8.3'
use_frameworks!

target 'TPPDF_Example' do
    pod 'TPPDF', :path => '../'
end

target 'TPPDF_Tests' do
    pod 'TPPDF', :path => '../'
    
    pod 'Quick'
    pod 'Nimble'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts "#{target.name}"
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
        end
    end
end
