language: objective-c
osx_image: xcode9
podfile: Example/Podfile
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/TPPDF.xcworkspace
  - IOS_FRAMEWORK_SCHEME="TPPDF"
  - EXAMPLE_SCHEME="TPPDF-Example"
  matrix:
     - DESTINATION="OS=8.4,name=iPhone 6 Plus"
     - DESTINATION="OS=9.3,name=iPhone 6s Plus"
     - DESTINATION="OS=11.0.1,name=iPhone 7 Plus"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME"  -destination "$DESTINATION" -configuration Debug    ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test   | xcpretty
  - xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_FRAMEWORK_SCHEME"  -destination "$DESTINATION" -configuration Release  ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test   | xcpretty
  - xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME"        -destination "$DESTINATION" -configuration Debug    ONLY_ACTIVE_ARCH=NO                         build | xcpretty
  - pod lib lint

before_install:
 - gem install cocoapods --pre --no-rdoc --no-ri --no-document
 - pod install --project-directory=Example
 
after_success:
  - bash <(curl -s https://codecov.io/bash) 
