name: TPPDF

targets:
  TPPDF:
    type: framework
    sources: Source
    platform: macOS
    deploymentTarget:
      iOS: 9.0
      macOS: 10.14
    settings:
      base:
        IPHONEOS_DEPLOYMENT_TARGET: 9
        MACOSX_DEPLOYMENT_TARGET: "10.14"
        ALLOW_TARGET_PLATFORM_SPECIALIZATION: YES
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        BUILD_LIBRARY_FOR_DISTRIBUTION: YES
        CLANG_CXX_LANGUAGE_STANDARD: "gnu++20"
        DEFINES_MODULE: NO
        SDKROOT: auto
        DEAD_CODE_STRIPPING: YES
        ENABLE_MODULE_VERIFIER: YES
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: "© techprimate GmbH 2024"
        LOCALIZATION_PREFERS_STRING_CATALOGS: YES
        MARKETING_VERSION: 1.0
        MODULE_VERIFIER_SUPPORTED_LANGUAGES: "objective-c objective-c++"
        MODULE_VERIFIER_SUPPORTED_LANGUAGE_STANDARDS: "gnu17 gnu++20"
        PRODUCT_BUNDLE_IDENTIFIER: com.techprimate.TPPDF
        PRODUCT_NAME: "$(TARGET_NAME:c99extidentifier)"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator macosx"
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "$(inherited)"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_INSTALL_OBJC_HEADER: NO
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        VERSION_INFO_PREFIX: ""
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/Frameworks"
          - "@loader_path/Frameworks"
        LD_RUNPATH_SEARCH_PATHS[sdk=macosx*]:
          - "@executable_path/../Frameworks"
          - "@loader_path/Frameworks"
      Debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
schemes:
  TPPDF:
    shared: true
    build:
      targets:
        TPPDF: all
