name: Danger

on:
  pull_request:
    branches:
      - main

jobs:
  job-danger:
    name: Review, Lint, Verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Danger
        uses: docker://ghcr.io/danger/danger-swift-with-swiftlint:3.15.0
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
